# NUMPY TOPIC 8-5-2020 ONLINE CLS

In [1]:
import numpy as np

In [2]:
data = np.loadtxt("populations (1).txt")
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [1]:
import math as m
print(m.pi)

3.141592653589793


In [2]:
import datetime
datetime.datetime.now()

datetime.datetime(2020, 5, 17, 18, 7, 35, 663410)

In [3]:
import datetime as dt
dt.datetime.now()

datetime.datetime(2020, 5, 17, 18, 7, 35, 820410)

In [4]:
from datetime import *

In [5]:
#from math import *
dir(math)

NameError: name 'math' is not defined

In [45]:
dir(datetime)

['__add__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 'astimezone',
 'combine',
 'ctime',
 'date',
 'day',
 'dst',
 'fold',
 'fromisoformat',
 'fromordinal',
 'fromtimestamp',
 'hour',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'microsecond',
 'min',
 'minute',
 'month',
 'now',
 'replace',
 'resolution',
 'second',
 'strftime',
 'strptime',
 'time',
 'timestamp',
 'timetuple',
 'timetz',
 'today',
 'toordinal',
 'tzinfo',
 'tzname',
 'utcfromtimestamp',
 'utcnow',
 'utcoffset',
 'utctimetuple',
 'weekday',
 'year']

In [46]:
# Numpy provides extension packages for multidimensional array
# closer to hardware
# Designed for scientific calculations
# also known as array computing
# mainly deals with matrix like 1D, 2D, .......nD
# 1D array is called as vectors
# 2D array is called as Matrix
# nD array is called as tensors

In [47]:
# how to import the module numpy
import numpy as np
# how to create a 1D array
abc = np.array([1,2,3,4])
type(abc)
abc1 = np.arange(10)
print(abc1)

[0 1 2 3 4 5 6 7 8 9]


In [48]:
# fast numerical calculations
# python list
lst = range(1000)
%timeit [i**2 for i in lst]

3.15 ms ± 319 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [49]:
#using numpy
lst = np.arange(1000)
%timeit lst**2

10.3 µs ± 453 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [50]:
# creating an array
# 1D
abc = np.array([1,2,3,4])
#to find the dimensions
abc.ndim

1

In [51]:
abc.shape

(4,)

In [52]:
len(abc)

4

In [53]:
# 2D
abc = np.array([[1,2,3,4],[5,6,7,8]])
abc.ndim

2

In [54]:
#abc.shape
len(abc)

2

In [55]:
#3D
abc = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(abc)
abc.ndim

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


3

In [56]:
abc.shape

(2, 2, 2)

In [57]:
a = np.arange(1,10,3)
print(a)

[1 4 7]


In [58]:
a = np.linspace(0,1)
a

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [59]:
a.shape

(50,)

In [60]:
a = np.linspace(0,10,6)
a

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [61]:
a.shape

(6,)

In [62]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
a = np.diag([1])
a

array([[1]])

In [65]:
b = np.diag([9,9,9,9])
b

array([[9, 0, 0, 0],
       [0, 9, 0, 0],
       [0, 0, 9, 0],
       [0, 0, 0, 9]])

In [66]:
b = np.diag([1,2,3,4])
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [67]:
# creating array using random
a = np.random.rand(10)     
a

array([0.84128927, 0.24524852, 0.37327612, 0.62104057, 0.26552236,
       0.75692059, 0.83663048, 0.45741134, 0.9752022 , 0.09360675])

In [68]:
# Standard distribution  ---- Gaussian distribution
a = np.random.randn(10)
a

array([-0.22863341, -1.97069053, -1.53774252, -0.50163961,  0.59630311,
        0.79572417,  0.55305107, -1.20054338, -1.21826202, -0.53929134])

In [69]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [70]:
nu = np.arange(20)
nu
print(nu)
#type(nu)
nu.dtype

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


dtype('int32')

In [71]:
nu = np.arange(20, dtype = 'float32')
nu

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.], dtype=float32)

In [72]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [73]:
a = np.diag([1,2,3,4])
a
a.dtype

dtype('int32')

In [74]:
b = np.array([1+2j,2+4j])
print(b)
b.dtype

[1.+2.j 2.+4.j]


dtype('complex128')

In [75]:
c = np.array([True,False,True])
print(c)
c.dtype

[ True False  True]


dtype('bool')

In [76]:
d = np.array(['gowthm','xyz'])
d.dtype

dtype('<U6')

In [77]:
# b = boolean
# i = signed integer
# u = unsigned integer
# f = floating point
# c = complex floating point
# m = time data
# M = datetime
# O = objects
# S 'a' = string
# U = unicode
# V = raw data

# docs.scipy.org/doc/numpy-1.10.1/user/basics.type.html

In [78]:
a = np.arange(20)
print(a)
print(a[9])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
9


In [79]:
a = np.diag([1,2,3,4])
#print(a[2][2])
print(a[2,2])

3


In [80]:
a[2,2] = 5 # ASsigning the value within matrix
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 4]])

In [81]:
# Slicing 
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [82]:
a[2:-4]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [83]:
a[2:15]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
a[2:15:3]

array([ 2,  5,  8, 11, 14])

In [85]:
a[::-3]

array([19, 16, 13, 10,  7,  4,  1])

In [86]:
b = np.arange(10)
print(b)
a[10:] = b[::-1]
a

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [87]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [88]:
b = a[::2]
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [89]:
np.shares_memory(a,b)

True

In [90]:
np.shares_memory(a,c)

False

In [91]:
a = np.arange(20)
c = a[::].copy() #force copy
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [92]:
c[13]

13

In [93]:
np.shares_memory(a,c)

False

In [94]:
# Element wise operations

a = np.array([1,2,3,4]) #vector

a + 10 #scalar



array([11, 12, 13, 14])

In [95]:
print(a/2)

[0.5 1.  1.5 2. ]


In [96]:
print(a*2)

[2 4 6 8]


In [97]:
print(a**2)

[ 1  4  9 16]


In [98]:
# All the arithematic operations

b =np.ones(5)
print(b)

[1. 1. 1. 1. 1.]


In [99]:
b = np.ones(4) + 1
print(a)
print(b)

print(a - b)

[1 2 3 4]
[2. 2. 2. 2.]
[-1.  0.  1.  2.]


In [100]:
print(a*b)
print(a/b)
print(a**2)

[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [101]:
c = np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [102]:
print(c*c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [103]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [104]:
a = np.array([[1,2,7,8],[3,4,9,8],[1,4,7,6],[5,4,9,4]])
print(a)
type(a)

[[1 2 7 8]
 [3 4 9 8]
 [1 4 7 6]
 [5 4 9 4]]


numpy.ndarray

In [105]:
a.ndim

2

In [106]:
a * a

array([[ 1,  4, 49, 64],
       [ 9, 16, 81, 64],
       [ 1, 16, 49, 36],
       [25, 16, 81, 16]])

In [107]:
# Comparisions also

a = np.array([1,2,3,4,5])
b = np.array([5,2,2,1,5])
a == b

array([False,  True, False, False,  True])

In [108]:
a >= b

array([False,  True,  True,  True,  True])

In [109]:
a < b

array([ True, False, False, False, False])

In [110]:
a <= b

array([ True,  True, False, False,  True])

In [111]:
np.array_equal(a,c)

False

In [112]:
#Logical operations

a = np.array([1,1,0,0])
b = np.array([1,0,1,0])

np.logical_and(a,b)

array([ True, False, False, False])

In [113]:
np.logical_or(a,b)

array([ True,  True,  True, False])

In [114]:
# OR GATE
0 0 = 0
1 0 = 1
0 1 = 1
1 1 = 1
# AND GATE
0 0 = 0
0 1 = 0
1 0 = 0
1 1 = 1


SyntaxError: invalid syntax (<ipython-input-114-7464ffbdb46c>, line 2)

In [115]:
# Trancedent fuctions
a = np.arange(4)
a

array([0, 1, 2, 3])

In [116]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [117]:
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654])

In [118]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [119]:
np.log(a)

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [120]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [121]:
# TRIGNOMETRIC TABLE
# angle = 0 30 45 60 90
#sin cos tan cosec sec cot
a = np.arange(5)
a.ndim

1

In [122]:
#SHAPE MISMATCH
print(a)
b = np.array([1,2,3])
a + b

[0 1 2 3 4]


ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [123]:
np.sum(a)

10

In [124]:
# SUM WITH AN AXIS CALCULATIONS
x = np.array([[1,2],[3,4]])
x.ndim

2

In [125]:
x.sum(axis = 0) # AXIS = 0 MEANS COLUMNS

array([4, 6])

In [126]:
x.sum(axis = 1) # AXIS = 1 MEANS ROWS

array([3, 7])

In [127]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [128]:
x.max()

19

In [129]:
x.min()

0

In [130]:
x.argmax() # arg means "it gives us max number's index value from  that array "

19

In [131]:
x.argmin() # arg means "it gives us min number's index value from  that array "

0

In [146]:
# STATISTICS
x = np.array([1,2,3,4])
y = np.array([[4,5,6,7],[8,9,10,11]])
print(y)

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [133]:
y.mean()

7.5

In [134]:
x.mean()

2.5

In [135]:
1+2+3+4

10

In [136]:
10/4

2.5

In [137]:
np.median(x)

2.5

In [138]:
x.std()

1.118033988749895

In [139]:
y.std()

2.29128784747792

In [153]:
data = np.array([
[1900.,30000.,4000.,48300.],
[1901.,47200.,6100.,48200.],
[1902.,70200.,9800.,41500.],
[1903.,77400.,35200.,38200.],
[1904.,36300.,59400.,40600.],
[1905.,20600.,41700.,39800.],
[1906.,18100.,19000.,38600.],
[1907.,21400.,13000.,42300.],
[1908.,22000.,8300.,44500.],
[1909.,25400.,9100.,42100.],
[1910.,27100.,7400.,46000.],
[1911.,40300.,8000.,46800.],
[1912.,57000.,12300.,43800.],
[1913.,76600.,19500.,40900.],
[1914.,52300.,45700.,39400.],
[1915.,19500.,51100.,39000.],
[1916.,11200.,29700.,36700.],
[1917.,7600.,15800.,41800.],
[1918.,14600.,9700.,43300.],
[1919.,16200.,10100.,41300.],
[1920.,24700.,8600.,47300.]])
print(data)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [154]:
data.shape

(21, 4)

In [155]:
data.ndim

2

In [156]:
data.dtype

dtype('float64')

In [157]:
data.mean()

24639.404761904763

In [160]:
np.median(data)

20050.0

In [161]:
np.std(data)

20329.69574416827

In [163]:
population = data[:,1:]
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [164]:
population.std(axis = 0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [165]:
population.mean(axis = 0)

array([34080.95238095, 20166.66666667, 42400.        ])

In [166]:
population.std(axis = 1)

array([18176.23601177, 19614.67704439, 24668.33327703, 19225.21492439,
       10030.73055941,  9530.41913501,  9458.79954798, 12319.18106946,
       14923.434219  , 13472.52347888, 15759.51211879, 16967.22330456,
       18751.53327064, 23553.39088586,  5266.87763291, 13018.02169644,
       10757.4263754 , 14578.82787546, 14819.88154099, 13501.68713737,
       15873.31793363])

In [167]:
population.mean(axis = 1)

array([27433.33333333, 33833.33333333, 40500.        , 50266.66666667,
       45433.33333333, 34033.33333333, 25233.33333333, 25566.66666667,
       24933.33333333, 25533.33333333, 26833.33333333, 31700.        ,
       37700.        , 45666.66666667, 45800.        , 36533.33333333,
       25866.66666667, 21733.33333333, 22533.33333333, 22533.33333333,
       26866.66666667])

In [168]:
# WHICH CARROT HAS THE HIGHEST POPULATION EACH YEAR
np.argmax(population,axis = 1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [196]:
# BROADCASTING MATRIX
import numpy as np

a = np.tile(np.arange(0,40,10) , (3,1))
# np.arange(0,40,10) will take size of matrix with difference 10.
# and 4,1 is called as repitions , these repititions can be of the size to print the matrix.4 rows and 1
# column
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [197]:
a = a.T
print(a)
a.ndim

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


2

In [198]:
b = np.array([0,1,2])
print(b)
b.ndim

[0 1 2]


1

In [199]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [202]:
a = np.arange(0,40,10)
print(a)

[ 0 10 20 30]


In [207]:
 a = a[: , np.newaxis] #if you want convert 1D array to 2D array then we use newaxis
a.ndim
a.shape

(4, 1, 1, 1, 1)

In [205]:
a

array([[[ 0]],

       [[10]],

       [[20]],

       [[30]]])

In [208]:
a + b

array([[[[[ 0,  1,  2]]]],



       [[[[10, 11, 12]]]],



       [[[[20, 21, 22]]]],



       [[[[30, 31, 32]]]]])

In [209]:
a = np.array([[1,3,5,7,8],[9,10,23,56,8]])
print(a)

[[ 1  3  5  7  8]
 [ 9 10 23 56  8]]


In [210]:
a.ravel()

array([ 1,  3,  5,  7,  8,  9, 10, 23, 56,  8])

In [211]:
a.T #Trancepose

array([[ 1,  9],
       [ 3, 10],
       [ 5, 23],
       [ 7, 56],
       [ 8,  8]])

In [212]:
a.T.ravel()

array([ 1,  9,  3, 10,  5, 23,  7, 56,  8,  8])

In [213]:
print(a.shape)

(2, 5)


In [214]:
b = a.shape
print(b)

(2, 5)


In [215]:
b = a.ravel()
print(b)

[ 1  3  5  7  8  9 10 23 56  8]


In [226]:
b = b.reshape(2,5)
print(b)

[[ 1  3  5  7  8]
 [ 9 10 67 56  8]]


In [227]:
b[1,2] = 67
print(b)

[[ 1  3  5  7  8]
 [ 9 10 67 56  8]]


In [228]:
b[0,1] = 9 # DOUBT DOUBLE NUMBERS CHANGE AT A TIME ????????????
print(b)

[[ 1  9  5  7  8]
 [ 9 10 67 56  8]]


In [229]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [230]:
a.resize(15)
print(a)

[0 1 2 3 4 5 6 7 8 9 0 0 0 0 0]


In [232]:
np.sort(b, axis = 1)

array([[ 1,  5,  7,  8,  9],
       [ 8,  9, 10, 56, 67]])

In [233]:
a = np.array([9,8,5,7])
b = np.argsort(a)
print(b)

[2 3 1 0]
